// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIkGmAqQN30IzU3g4LBer2Hyqdz4uhG4c',
    appId: '1:1073703968944:web:6ac29fd47df76efe8a5b75',
    messagingSenderId: '1073703968944',
    projectId: 'dnsc-events',
    authDomain: 'dnsc-events.firebaseapp.com',
    storageBucket: 'dnsc-events.firebasestorage.app',
    measurementId: 'G-1JJ13S6PCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD66zMRU5c20HQc44YGRSfiT9Re7AuTcaM',
    appId: '1:1073703968944:android:062f8d247d01327f8a5b75',
    messagingSenderId: '1073703968944',
    projectId: 'dnsc-events',
    storageBucket: 'dnsc-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5k-QOqzvuqtX-Ff44H52sWSDaTTgDeLs',
    appId: '1:1073703968944:ios:64392323fd27a48c8a5b75',
    messagingSenderId: '1073703968944',
    projectId: 'dnsc-events',
    storageBucket: 'dnsc-events.firebasestorage.app',
    iosBundleId: 'com.example.dnscEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5k-QOqzvuqtX-Ff44H52sWSDaTTgDeLs',
    appId: '1:1073703968944:ios:64392323fd27a48c8a5b75',
    messagingSenderId: '1073703968944',
    projectId: 'dnsc-events',
    storageBucket: 'dnsc-events.firebasestorage.app',
    iosBundleId: 'com.example.dnscEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIkGmAqQN30IzU3g4LBer2Hyqdz4uhG4c',
    appId: '1:1073703968944:web:a45918d3d8acee708a5b75',
    messagingSenderId: '1073703968944',
    projectId: 'dnsc-events',
    authDomain: 'dnsc-events.firebaseapp.com',
    storageBucket: 'dnsc-events.firebasestorage.app',
    measurementId: 'G-6F8S5P0KTW',
  );
}
